### ISSUE TITLE
Null Pointer Exception on Build - General Logging and Error Handling

### ISSUE THREAD

**Issue by domoran** [sngular/scs-multiapi-plugin#151]
I started checking out the multiapi-maven-plugin and I ran it with the following example from the OpenAPI Studio: 

``` 
asyncapi: '2.5.0'
info:
  title: Account Service
  version: 1.0.0
  description: This service is in charge of processing user signups
channels:
  user/signedup:
    subscribe:
      message:
        $ref: '#/components/messages/UserSignedUp'
components:
  messages:
    UserSignedUp:
      payload:
        type: object
        properties:
          displayName:
            type: string
            description: Name of the user
          email:
            type: string
            format: email
            description: Email of the user
```

The maven build fails with a null pointer exception, because (as I found out after looking into the code), there is no "operationId" parameter present in the channel item. 

Expected Behaviour would be, that the generator either skips the operation with a warning or creates a default operationId (e.g. user_signedup). While looking through the code I notices, that there seems to be no error handling or logging in place. 

Exceptions are caught and handled with printstacktrace like in net.coru.api.generator.plugin.asyncapi.AsyncApiGenerator.processFileSpec(List<SpecFile>):
```      ...
      } catch (final TemplateException | IOException e) {
        e.printStackTrace();
      }
```
If this is of general interest, I would like to work on the error handling and logging by introducing a LoggingInterface in the multiapi-engine through which info, error and debug messages can be communicated to the calling plugin. In the maven plugin we would use the maven logger to implement this interface, in the gradle plugin the gradle logger.

**Comment by dianaGomezGar** [comment]
Hi @domoran, 

This is an open project, so you can contribute any time you want.  But it’s important to follow our contributing rules. You can check them at this link:

https://github.com/corunet/scs-multiapi-plugin/blob/main/CONTRIBUTING.md


Thank you so much for your interest and participation!

**Comment by adrien1212** [comment]
Hi

I don't achieve to create a pull reques but please consider the following solution


**Disclaimer :**
This code resolve the exception raised, nevertheless any Java class is created ?! Normal or not ?

In the method `getOperationId` from the class `AsyncApiGenerator` add the following code
```java
getOperationId() {
    if(getChannelPayload(channel).get(OPERATION_ID) == null) {
	return null;
    }
    ...
}
```

In the method `isValidOperation` replace the first condition by
```java
isValidOperation(...) {
    if (operation != null && operationId != null) {     // add -> && operationId != null
}
```
