### ISSUE TITLE
Version Confusion as examples use different plugin versions

### ISSUE THREAD

**Issue by domoran** [sngular/scs-multiapi-plugin#152]
The first example in the README.md file contains a maven version 3.2.0 for the plugin which is long outdated. Other examples mention 4.0.0 while the most current version is 4.2.4 (and soon 4.2.5). 

The code examples should be moved to the Github Pages Documentation, where the latest release version is automatically filled in.

**Comment by dianaGomezGar** [comment]
Hi @domoran, 

We usually use the wiki section of our documentation. We are in process to create it and keep it update for an easier use of this plugin. 
We will also investigate the Github Pages Documentation to valuate if it's really useful for us. 

Thank you for your time. We let you know something as soon as possible.
Cheers!

**Comment by davidgarciago** [comment]
Hello again @domoran,

I have changed manually the versions in the main branch to match the latest version. Our policy is to use only github's wiki for documentation, so we are going to wait for our technical writers team to create the corresponding pages in it. They will get updated via github actions everytime the main branch gets new code merged. All this will take a while so please be patient.

Thank you for your support!

**Comment by jemacineiras** [comment]
Change as introduced as a checklist for the team
