### ISSUE TITLE
Support for complex types in lists and maps

### ISSUE THREAD

**Issue by davidgarciago** [sngular/scs-multiapi-plugin#165]
As a developer i found that the only way to use complex types in lists and maps is to create a reference as shown below:

    test:
      type: object
      required:
      - id
      properties:
        id:
          type: string
      additionalProperties:
        $ref: '#components/schemas/subtest'

It would be perfect if i could add object references to any object using unnamed objects as shown in this other schema:

    test:
      type: object
      required:
      - id
      properties:
        id:
          type: string
      additionalProperties:
        type: array
        items:
          $ref: "#/components/schemas/arraySchema"

Currently that schema generates Map<String, Object> and the expected result is Map<String, List< ArraySchemaDTO >>

**Comment by RaulBejaranoSngular** [comment]
According to [OpenAPI Specification](https://swagger.io/specification/)

> additionalProperties - Value can be boolean or object. Inline or referenced schema MUST be of a Schema Object and not a standard JSON Schema. Consistent with JSON Schema, additionalProperties defaults to true.

So this enhacement is not compatible with the specification and will not be implemented.

**Comment by RaulBejaranoSngular** [comment]
According to [OpenAPI Specification](https://swagger.io/specification/)

> additionalProperties - Value can be boolean or object. Inline or referenced schema MUST be of a Schema Object and not a standard JSON Schema. Consistent with JSON Schema, additionalProperties defaults to true.
