### ISSUE TITLE
pom file is not uploaded to maven central

### ISSUE THREAD

**Issue by mlemnian** [sngular/scs-multiapi-plugin#194]
There is no pom file uploaded to the maven central repo.

see e.g. https://repo1.maven.org/maven2/com/sngular/scs-multiapi-maven-plugin/4.5.0/

This will cause problems using that particular release in any build.

```
[WARNING] The POM for com.sngular:scs-multiapi-maven-plugin:jar:4.5.0 is missing, no dependency information available
```

This problem is also present in all newer releases!

Maybe consider [jreleaser](https://github.com/jreleaser/jreleaser/releases) plugin?

**Comment by jemacineiras** [comment]
Hi @mlemnian,

we think we sort this out in another issue. Can you please check if the actual deployments works for you?

**Comment by jemacineiras** [comment]
Hi @mlemnian,

 Can you please check if the actual deployments works for you?

Cheers

**Comment by AdrianLagarteraSngular** [comment]
Closed because no new related errors have occurred and it is correctly deployed in the maven repository.
