### ISSUE TITLE
[AsyncApi] The plugin crash if the definition has not a schema (IndexOutOfBoundsException)

### ISSUE THREAD

**Issue by alfredo9f** [sngular/scs-multiapi-plugin#214]
# What happens
If you have a definition with an external file with the schema and any schema in the asyncapi file, the plugin crash with an  `IndexOutOfBoundsException`

![image](https://user-images.githubusercontent.com/126802441/234859701-71600186-f39a-4f4b-97a7-bea902b04d00.png)

### AsyncApi file
```
asyncapi: 2.3.0
info:
  title: Customer Position
  version: 1.0.0
  description: Customer Position Service
servers:
  development:
    url: localhost:9092
    description: Development server
    protocol: kafka
    protocolVersion: 0.9.1
channels:
  importProduct:
    subscribe:
      operationId: "importProduct"
      message:
        payload:
          $ref: 'schema/import_product.avsc'
  productEmitter:
    publish:
      operationId: "productEmitter"
      message:
        payload:
          $ref: 'schema/import_product.avsc'
```

### Avro file
```
{
  "type": "record",
  "name": "ImportProductEvent",
  "namespace": "com.sngular.customerpositionpoc.api.model",
  "doc": "Container for the product event",
   "fields": [
    {
       "name": "customerId",
       "type": "string",
       "doc": "Customer Id"
    },
    {
       "name": "productId",
       "type": "string",
       "doc": "Product Id"
    },
    {
       "name": "productType",
       "type": "string",
       "doc": "Product Type"
    }
  ]
}
```

# What is expected
The plugin should generate the interfaces classes

**Comment by jemacineiras** [comment]
Hi @alfredo9f,

Did you had a chance to test #208 in case it fix your problem?

**Comment by alfredo9f** [comment]
> Hi @alfredo9f,
> 
> Did you had a chance to test #208 in case it fix your problem?

Hi @jemacineiras , yes, the bug was solved in the other issue. I have a test for this concrete scenery so if you want I could add it or close this ticket if is not necessary.
