### ISSUE TITLE
[AsyncApi] fix ModelClassException pakage

### ISSUE THREAD

**Issue by marioTemprano** [sngular/scs-multiapi-plugin#230]
As a developer, I want that the package of the ModelClassException and its imports matches to avoid errors. The exception is not  generated in the correct path, it needs to be fixed too.

This is how the import is generated:
<img width="884" alt="image" src="https://github.com/sngular/scs-multiapi-plugin/assets/86358300/e7a63cff-114e-43a9-b655-b92db23e3034">

This is how the exception class is generated:
<img width="814" alt="image" src="https://github.com/sngular/scs-multiapi-plugin/assets/86358300/0af783e6-edd7-49c8-8944-f465bd24ef57">

This is the generated folder structure:
<img width="352" alt="image" src="https://github.com/sngular/scs-multiapi-plugin/assets/86358300/c1d38590-c118-4570-8e8d-236d5ee95f18">

**Comment by AdrianLagarteraSngular** [comment]
Duplicated on #229
