### ISSUE TITLE
ConsumerKafkaBinding

### ISSUE THREAD

**Issue by jgonzalezlawyer** [sngular/scs-multiapi-plugin#268]
Hi,

the ConsumerKafkaBinding generates a class that not compile
https://github.com/sngular/scs-multiapi-plugin/blob/main/multiapi-engine/src/main/resources/templates/asyncapi/templateConsumersWithKafkaBindings.ftlh

I propose:
**templateConsumersWithKafkaBindings.ftlh**
package ${subscribePackage};

import java.util.function.Consumer;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
<#list subscribeMethods as method>
import ${method.classNamespace}.${method.className}<#if subscribeEntitiesSuffix?has_content>${subscribeEntitiesSuffix}</#if>;
<#if method.keyClassNamespace?has_content>
import ${method.keyClassNamespace}.${method.keyClassName};
</#if>
</#list>
import ${subscribePackage}.MessageWrapper;
import org.springframework.messaging.Message;
import org.springframework.kafka.support.KafkaHeaders;

@Configuration
public class ${subscribeClassName?cap_first} {

  <#list subscribeMethods as method>
  private final I${method.operationId?cap_first} ${method.operationId?uncap_first};
  </#list>

  protected ${subscribeClassName?cap_first}(<#list subscribeMethods as method>final I${method.operationId?cap_first} ${method.operationId?uncap_first}<#sep>, </#list>) {
    <#list subscribeMethods as method>
    this.${method.operationId?uncap_first} = ${method.operationId?uncap_first};
    </#list>
  }

  <#list subscribeMethods as method>
  @Bean
  public Consumer<Message<${method.className}<#if subscribeEntitiesSuffix?has_content>${subscribeEntitiesSuffix}</#if>>> ${method.operationId?uncap_first}() {
    return value -> {
      final MessageWrapper messageWrapper = MessageWrapper.builder().payload(value.getPayload()).key(value.getHeaders().get(KafkaHeaders.KEY)).build();
      ${method.operationId?uncap_first}.${method.operationId?uncap_first}(messageWrapper);
    };
  }

  </#list>

}

**templateMessageWrapper.ftlh**
package ${wrapperPackage};

import lombok.Builder;

@Builder
public class MessageWrapper<T, Y> {

  private T payload;

  private Y key;

  public MessageWrapper(final Y key, final T payload) {
    this.payload = payload;
    this.key = key;
  }

  public T getPayload() {
   return payload;
  }

  public void setPayload(T payload) {
    this.payload = payload;
  }

  public Y getKey() {
    return key;
  }

  public void setKey(Y key) {
    this.key = key;
  }

}

**interfaceConsumerWithKafkaBindings.ftlh**
package ${subscribePackage};

import ${method.classNamespace}.${method.className}<#if subscribeEntitiesSuffix?has_content>${subscribeEntitiesSuffix}</#if>;
<#if method.keyClassNamespace?has_content>
import ${method.keyClassNamespace}.${method.keyClassName};
</#if>
import ${subscribePackage}.MessageWrapper;

public interface I${method.operationId?cap_first} {

  void ${method.operationId?uncap_first}(final MessageWrapper<${method.className}<#if subscribeEntitiesSuffix?has_content>${subscribeEntitiesSuffix}</#if>, ${method.keyClassName}> value);
}

**Comment by jemacineiras** [comment]
Hi @jgonzalezlawyer,

I'll check it and prepare a fix asap.

Cheers

**Comment by jemacineiras** [comment]
Hi @jgonzalezlawyer,
There is a possible fix in a branch linked to this issue.
Can you test it that works for you?

Cheers

**Comment by jemacineiras** [comment]
Hi @jgonzalezlawyer,
There is a possible fix in a branch linked to this issue.
Can you test it that works for you?

Cheers
