### ISSUE TITLE
[AsyncAPI] CompilationFailureException when using integer minimum and maximum

### ISSUE THREAD

**Issue by gaby-roland** [sngular/scs-multiapi-plugin#270]
It seems like using `minimum` and `maximum` on an `integer` causes a CompilationFailureException as soon as another integer is introduced.

I have a very simple sample API spec with a few integer types. The moment I add `minimum` or `maximum` to one of the integer types, it starts causing a `CompilationFailureException`.

I can use `minimum` and `maximum` as long as I only have one integer in my schema. But adding a second integer breaks it.
I can also have as many integers as I want if I don't specify `minimum` or `maximum`.

For example, this API spec works for me, and produces the correct classes:
```
asyncapi: "2.0.0"
info:
  title: Demo API
  version: "1.0.0"

channels:
  user/signedup:
    subscribe:
      operationId: emitUserSignUpEvent
      message:
        $ref : '#/components/messages/UserSignedUp'

components:
  messages:
    UserSignedUp:
      name: userSignedUp
      title: User signed up event
      summary: Inform about a new user registration in the system
      contentType: application/json
      payload:
        $ref: '#/components/schemas/userSignedUpPayload'

  schemas:
    userSignedUpPayload:
      type: object
      properties:
        firstName:
          type: string
          description: "foo"
        lastName:
          type: string
          description: "bar"
        age:
          type: integer
          minimum: 0
          maximum: 200
```

But as soon as I add a second integer under `age` 
```
...
        age:
          type: integer
          minimum: 0
          maximum: 200
        pin:
          type: integer
```

I get the following failure:
```
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (d
efault-compile) on project asyncapi-demo-service-api: Compilation failure
...
Caused by: org.apache.maven.plugin.compiler.CompilationFailureException: Compilation failure
```

**Comment by jemacineiras** [comment]
Hi @gaby-roland,
thanks for the feedback, I'll check it and will provide a fix asap.
Cheers

**Comment by jemacineiras** [comment]
Hi @gaby-roland,

I modified an existing test to reproduce your issue and provide a small fix. Do you mind trying it?
BTW, I found we have a problem in how we create the custom validators, that will try to address soon. I think for now, we can only support custom validators about max and min for a single data type. I am considering which will be the best approach .

Cheers

**Comment by gaby-roland** [comment]
Hi @jemacineiras 

Thanks for the quick responses.
With your changes I got a new Compilation failure. 
![image](https://github.com/sngular/scs-multiapi-plugin/assets/61486354/845a7e45-603b-49ec-bfc4-3d834ddf9b65)

This is the generated class, it looks like it duplicates the class line right after defining the `maximum` member variable. Lines 8-10 are duplicated on lines 11-13. Hope this helps.

**Comment by gaby-roland** [comment]
@jemacineiras Your latest commit seems to work well! It generates the min/max validators properly.
I understand that for now we can only use min/max validation for a single type, and that is fine for my use case.
Thanks for the quick responses and for working a fix quickly!
