### ISSUE TITLE
[AsyncAPI] NullPointerException in MapperContentUtil.java

### ISSUE THREAD

**Issue by gaby-roland** [sngular/scs-multiapi-plugin#271]
I keep getting `NullPointerException` errors originating in `MapperContentUtil`.
Specifically, line 390.

```
         if (value.has(REF)) {
            typeObject = MapperUtil.getRef(value, prefix, suffix);
          }
          field.setImportClass(getImportClass(typeObject));
          field.setDataType(typeObject);
          final String[] path = MapperUtil.splitName(value.get(REF).textValue());
```
It looks like on the last line in the snippet, `value.get(REF)` is null, which explains why a few line before it there is a `if (value.has(REF))`, but this check is not taken into consideration on 390 and `value.get(REF)` is assumed to be non-null.

I saw this error whenever I try have an object nested inside another object, for example in the yaml below, `someOtherObject` is nested inside of `userSignedUpPayload`:
```
asyncapi: "2.0.0"
info:
  title: Demo API
  version: "1.0.0"

channels:
  user/signedup:
    subscribe:
      operationId: emitUserSignUpEvent
      message:
        $ref : '#/components/messages/UserSignedUp'

components:
  messages:
    UserSignedUp:
      name: userSignedUp
      title: User signed up event
      summary: Inform about a new user registration in the system
      contentType: application/json
      payload:
        $ref: '#/components/schemas/userSignedUpPayload'

  schemas:
    userSignedUpPayload:
      type: object
      properties:
        firstName:
          type: string
          description: "foo"
        lastName:
          type: string
          description: "bar"
        email:
          type: string
          format: email
          description: "baz"
        createdAt:
          type: string
          format: date-time
        someOtherObject:
          type: object
          properties:
            property1:
              type: string
            property2:
              type: integer
```

This causes the following error:
```
Caused by: java.lang.NullPointerException
    at com.sngular.api.generator.plugin.asyncapi.util.MapperContentUtil.setFieldType (MapperContentUtil.java:390)
    at com.sngular.api.generator.plugin.asyncapi.util.MapperContentUtil.processFieldObjectList (MapperContentUtil.java:245)
    at com.sngular.api.generator.plugin.asyncapi.util.MapperContentUtil.processFieldObject (MapperContentUtil.java:156)
    at com.sngular.api.generator.plugin.asyncapi.util.MapperContentUtil.getFields (MapperContentUtil.java:128)
    at com.sngular.api.generator.plugin.asyncapi.util.MapperContentUtil.buildSchemaObject (MapperContentUtil.java:82)
    at com.sngular.api.generator.plugin.asyncapi.util.MapperContentUtil.mapComponentToSchemaObject (MapperContentUtil.java:66)
    at com.sngular.api.generator.plugin.asyncapi.AsyncApiGenerator.fillTemplateFactory (AsyncApiGenerator.java:538)
    at com.sngular.api.generator.plugin.asyncapi.AsyncApiGenerator.processSubscribeMethod (AsyncApiGenerator.java:524)
    at com.sngular.api.generator.plugin.asyncapi.AsyncApiGenerator.processOperation (AsyncApiGenerator.java:336)
    at com.sngular.api.generator.plugin.asyncapi.AsyncApiGenerator.processFileSpec (AsyncApiGenerator.java:172)
```

**Comment by jemacineiras** [comment]
HI @gaby-roland,

Looks like you found a hole in our AsyncApi specification support. I'll check it and provide a solution ASAP.

Cheers

**Comment by jemacineiras** [comment]
HI @gaby-roland,

I provide a fix in a branch attached to this issue. Do you mind test if it works for you?

Cheers

**Comment by gaby-roland** [comment]
Hi @jemacineiras 

I pulled and built your branch. It seems to get a bit farther now, but I get this error now:

```
Caused by: org.apache.maven.plugin.compiler.CompilationFailureException: Compilation failure
/C:/Development/Projects/apis/asyncapi/core/asyncapi-demo-service-api/target/generated-sources/apig
enerator/com/boeing/aga/sps/apis/asyncapi/demo/generated/types/SomeOtherObject.java:[1,63] <identif
ier> expected
```

When I look at my generated classes, it seems to be appending a `.` at the end of the package, like it's expecting 1 more package identifier. But the class is in `com.boeing.aga.sps.apis.asyncapi.demo.generated.types`
![image](https://github.com/sngular/scs-multiapi-plugin/assets/61486354/d3b519e4-9130-461c-ae04-6b1360958638)

**Comment by gaby-roland** [comment]
Hi @jemacineiras 

I pulled and built your branch. It seems to get a bit farther now, but I get this error now:

```
Caused by: org.apache.maven.plugin.compiler.CompilationFailureException: Compilation failure
/C:/Development/Projects/apis/asyncapi/core/asyncapi-demo-service-api/target/generated-sources/apig
enerator/com/test/apis/asyncapi/demo/generated/types/SomeOtherObject.java:[1,63] <identif
ier> expected
```

When I look at my generated classes, it seems to be appending a `.` at the end of the package, like it's expecting 1 more package identifier. But the class is in `com.test.apis.asyncapi.demo.generated.types` (see line 1)
![image](https://github.com/sngular/scs-multiapi-plugin/assets/61486354/5f35acb9-8f52-4d78-bf03-545d6e4c7a2a)

**Comment by jemacineiras** [comment]
Hi @gaby-roland,
That is odd, I added a test with your schema and generates all files property (testNestedObjectIssue). Do you mind sharing the configuration part you have in the plugin?
Cheers

**Comment by gaby-roland** [comment]
@jemacineiras Sure! Here is my plugin configuration in my pom.xml

```xml
      <plugin>
        <groupId>com.sngular</groupId>
        <artifactId>scs-multiapi-maven-plugin</artifactId>
        <version>${scs.multiapi.maven.plugin.version}</version>
        <executions>
          <execution>
            <phase>generate-sources</phase>
            <goals>
              <goal>asyncapi-generation</goal>
            </goals>
            <configuration>
              <specFiles>
                <specFile>
                  <filePath>${asyncapi.spec}</filePath>
                  <consumer>
                    <apiPackage>${project.groupId}.demo.generated.api.consumer</apiPackage>
                    <modelPackage>${project.groupId}.demo.generated.types</modelPackage>
                  </consumer>
                  <supplier>
                    <apiPackage>${project.groupId}.demo.generated.api.producer</apiPackage>
                    <modelPackage>${project.groupId}.demo.generated.types</modelPackage>
                  </supplier>
                </specFile>
              </specFiles>
            </configuration>
          </execution>
        </executions>
      </plugin>
 ```

**Comment by gaby-roland** [comment]
This is the generated code by the way. It looks like it places `SomOtherObject` outside of the `schemas` package.
![image](https://github.com/sngular/scs-multiapi-plugin/assets/61486354/416542c9-1cc2-4a0b-be3e-91ed234c766e)

**Comment by gaby-roland** [comment]
This is the generate code structure btw, it looks like it places `SomeOtherObject` outside of the `schemas` package:
![image](https://github.com/sngular/scs-multiapi-plugin/assets/61486354/8125d6d4-9a6d-423a-8472-216a24d21e49)

**Comment by jemacineiras** [comment]
Thanks,

I found strange this part
` <supplier>
                    <apiPackage>${project.groupId}.demo.generated.api.producer</apiPackage>
                    <modelPackage>${project.groupId}.demo.generated.types</modelPackage>
                  </supplier>`
But there is no producer part defined in the API definition.
That is correct?

**Comment by gaby-roland** [comment]
Yeah I think that's because I just don't have any `publish` operations/channels, so that package is empty right now. I just have 1 `subscribe` channel for now in my demo but my operational code will have both.

**Comment by jemacineiras** [comment]
Yes, that was the problem. But I think I found the key, do you mind testing this fix?

**Comment by gaby-roland** [comment]
With the latest changes, it seems like the `supplier` package and all the `publish` channels are completely missing.
Here is the same yaml as in the original problem, but with the added `publish` channel. I also updated my plugin configuration to add a `<supplier>` section. But the publish channels don't get generated.

```yaml
asyncapi: "2.0.0"
info:
  title: Demo API
  version: "1.0.0"

channels:
  user/signedup:
    subscribe:
      operationId: emitUserSignUpEvent
      message:
        $ref : '#/components/messages/UserSignedUp'
    publish:
      operationId: onUserSignUp
      message:
        $ref: '#/components/messages/UserSignedUp'

components:
  messages:
    UserSignedUp:
      name: userSignedUp
      title: User signed up event
      summary: Inform about a new user registration in the system
      contentType: application/json
      payload:
        $ref: '#/components/schemas/userSignedUpPayload'

  schemas:
    userSignedUpPayload:
      type: object
      properties:
        firstName:
          type: string
          description: "foo"
        lastName:
          type: string
          description: "bar"
        email:
          type: string
          format: email
          description: "baz"
        createdAt:
          type: string
          format: date-time
        someOtherObject:
          type: object
          properties:
            property1:
              type: string
            property2:
              type: integer
```
