### ISSUE TITLE
[AsyncAPI] Supplier package and channels are not being generated

### ISSUE THREAD

**Issue by gaby-roland** [sngular/scs-multiapi-plugin#278]
With the latest 4.9.9 version, it seems like the `supplier` package and all the `publish` channels are completely missing.
Here is the sample yaml, containing a single `publish` and `subscribe` channel. I also updated my plugin configuration to add a `<supplier>` section. But the publish channels don't get generated.

```yaml
asyncapi: "2.0.0"
info:
  title: Demo API
  version: "1.0.0"

channels:
  user/signedup:
    subscribe:
      operationId: emitUserSignUpEvent
      message:
        $ref : '#/components/messages/UserSignedUp'
    publish:
      operationId: onUserSignUp
      message:
        $ref: '#/components/messages/UserSignedUp'

components:
  messages:
    UserSignedUp:
      name: userSignedUp
      title: User signed up event
      summary: Inform about a new user registration in the system
      contentType: application/json
      payload:
        $ref: '#/components/schemas/userSignedUpPayload'

  schemas:
    userSignedUpPayload:
      type: object
      properties:
        firstName:
          type: string
          description: "foo"
        lastName:
          type: string
          description: "bar"
        email:
          type: string
          format: email
          description: "baz"
```

**Comment by gaby-roland** [comment]
After doing a bit more testing, I found out this problem only occurs if both your publish and subscribe channels are under the same channel ID, like this.

```yaml
channels:
  user/signedup:
    subscribe:
      operationId: emitUserSignUpEvent
      message:
        $ref : '#/components/messages/UserSignedUp'
    publish:
      operationId: onUserSignUp
      message:
        $ref: '#/components/messages/UserSignedUp'
```

However, if the 2 channels were separated under different IDs, the code generates both:
```
channels:
  user/signedup:
    subscribe:
      operationId: emitUserSignUpEvent
      message:
        $ref : '#/components/messages/UserSignedUp'
  user/signedup2:
    publish:
      operationId: onUserSignUp
      message:
        $ref: '#/components/messages/UserSignedUp'
```

**Comment by jemacineiras** [comment]
Hi @gaby-roland,
this is the expected behaviour. 
Why you want to produce something onto a topic you are reading? you can end on an endless loop.
Usually or you read or you write on a topic.. what use case you need to read and write on the same topic and handle duplicate data by yourself?
Cheers

**Comment by jemacineiras** [comment]
HI @gaby-roland,
That the explanation helps you?

Cheers

**Comment by gaby-roland** [comment]
@jemacineiras Thanks for the response, this is fine for now, can close the issue 👍
