### ISSUE TITLE
[AsyncAPI] Message payload missing all properties except for referenced schema property

### ISSUE THREAD

**Issue by gaby-roland** [sngular/scs-multiapi-plugin#279]
Sorry about the several issues I've opened as I work through switching to using this library for code generation.

It seems like if you have a message payload that defines several properties, one of which is a schema reference, only the schema reference will be generated inside the class, and the rest of the properties are skipped. Here is an example yaml to reproduce:

```yaml
asyncapi: "2.0.0"
info:
  title: Demo API
  version: "1.0.0"

channels:
  user/signedup:
    subscribe:
      operationId: emitUserSignUpEvent
      message:
        $ref : '#/components/messages/UserSignedUp'
    publish:
      operationId: onUserSignUp
      message:
        $ref: '#/components/messages/UserSignedUp'

components:
  messages:
    UserSignedUp:
      name: userSignedUp
      title: User signed up event
      summary: Inform about a new user registration in the system
      contentType: application/json
      payload:
        type: object
        properties:
          id:
            type: string
          details:
            $ref: '#/components/schemas/UserDetails'

  schemas:
    UserDetails:
      type: object
      properties:
        firstName:
          type: string
          description: "foo"
        lastName:
          type: string
          description: "bar"
        email:
          type: string
          format: email
          description: "baz"
```

Notice that my `UserSignedUp` message has 2 properties, an id (string) and a details object that is defined in the schema. When the code is generated, my `UserSignedUp` class will only have the `details` member variable, and nothing else. The `id` and any other properties in the yaml file are completely skipped.

**Comment by jemacineiras** [comment]
Hi @gaby-roland,
No problem for open as many issues as you need. It helps us to get perfection in our code. We just make a huge refactor 2 versions ago and now things are popping up.
Really appreciate your effort and we are here to assist you whatever you need.
I´ll take a look to your issues.

Cheers

**Comment by gaby-roland** [comment]
If your message has no schema references, that message will not be generated at all and a compilation failure occurs.

**Comment by gaby-roland** [comment]
Sorry I should have been more clear, if my message defines a payload that doesn't reference a schema, but instead lists all the properties, for example:
```yaml
asyncapi: "2.0.0"
info:
  title: Demo API
  version: "1.0.0"

channels:
  user/signedup:
    subscribe:
      operationId: emitUserSignUpEvent
      message:
        $ref : '#/components/messages/UserSignedUp'
    publish:
      operationId: onUserSignUp
      message:
        $ref: '#/components/messages/UserSignedUp'

components:
  messages:
    UserSignedUp:
      name: userSignedUp
      title: User signed up event
      summary: Inform about a new user registration in the system
      contentType: application/json
      payload:
        type: object
        properties:
          firstName:
            type: string
            description: "foo"
          lastName:
            type: string
            description: "bar"
          email:
            type: string
            format: email
            description: "baz"
```

This is a valid API schema, but I get a compilation failure.
It seems this library wants us to remove all the properties into a dedicated schema like this:

```yaml
asyncapi: "2.0.0"
info:
  title: Demo API
  version: "1.0.0"

channels:
  user/signedup:
    subscribe:
      operationId: emitUserSignUpEvent
      message:
        $ref : '#/components/messages/UserSignedUp'
    publish:
      operationId: onUserSignUp
      message:
        $ref: '#/components/messages/UserSignedUp'

components:
  messages:
    UserSignedUp:
      name: userSignedUp
      title: User signed up event
      summary: Inform about a new user registration in the system
      contentType: application/json
      payload:
        $ref: '#/components/schemas/userSignedUpPayload'

  schemas:
    userSignedUpPayload:
      type: object
      properties:
        firstName:
          type: string
          description: "foo"
        lastName:
          type: string
          description: "bar"
        email:
          type: string
          format: email
          description: "baz"
  ```

This schema will generate as expected.

**Comment by jemacineiras** [comment]
No, your way should work. Unless we were facing another issue. I am sure because I implemented that myself.
I will take a look

**Comment by jemacineiras** [comment]
Hi @gaby-roland,

I have a PR with a candidate to fix. I also make some changes about what we are going to generate, so no more Messages classes with only a payload. 
Meaning that we are heading to the 5.0.0 version.
Do you mind to test if that version solve your problem?

Cheers

**Comment by gaby-roland** [comment]
Version 5.0.0 fixed the problem described in this issue. Thanks!
