### ISSUE TITLE
[AsyncApi] $ref resultion are always a class

### ISSUE THREAD

**Issue by devNbis** [sngular/scs-multiapi-plugin#293]
I've fired out that there is a problem on references !type:object . It creates always the object name like a class.
```json
"EventDataDTO": {
    "name":" EventDataDTO",
     "$id":"EventDataDTO",
     "title": "Event",
     "type": "object",          
     "properties": {
          "name": {
            "type": "string"
          },
          "currency": {
                "$ref": "#/components/schemas/Currency"
           }
      }
 },
 "Currency": {
     "type": "string",
       "format": "currency",
 }
```
Will result as
```java
@JsonProperty(value ="leadingCurrency") private Currency leadingCurrency;
````

But it should be
```java
@JsonProperty(value ="leadingCurrency") private String leadingCurrency;
```

**Comment by jemacineiras** [comment]
I will take a look

**Comment by jemacineiras** [comment]
Hi @devNbis,
do you mind to try the brach attached to this issue to test the solution?

Cheers

**Comment by devNbis** [comment]
Hi @jemacineiras 
I've test it the sample which is inside of https://studio.asyncapi.com/. 
It generates the model now as String correctly. But end with an error

`[ERROR] Failed to execute goal com.sngular:scs-multiapi-maven-plugin:5.0.2:asyncapi-generation (default) on project consuming-retry: Execution default of goal com.sngular:scs-multiapi-maven-plugin:5.0.2:asyncapi-generation failed: AsyncApi -> File System error trying to manipulate files: The following has evaluated to null or missing:                              
[ERROR] ==> value  [in template "templateSchema.ftlh" at line 141, column 7]
[ERROR] 
[ERROR] ----
[ERROR] Tip: If the failing expression is known to legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??                                                                                                                                                              
[ERROR] ----
`

**Comment by jemacineiras** [comment]
Hi @devNbis ,

I´ll take a look,

Cheers
