### ISSUE TITLE
Error when executing asyncapi-generation

### ISSUE THREAD

**Issue by landoephan** [sngular/scs-multiapi-plugin#294]
I'm trying to use the plugin v5.0.1 in a maven context. I'm having an asyncapi yaml file specified and referenced in my pom. My pom.xml looks like this:
```
    <build>
        <plugins>
            <plugin>
                <groupId>com.sngular</groupId>
                <artifactId>scs-multiapi-maven-plugin</artifactId>
                <version>5.0.1</version>
                <executions>
                    <execution>
                        <id>asyncapi</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>asyncapi-generation</goal>
                        </goals>
                        <configuration>
                            <specFiles>
                                <specFile>
                                    <filePath>${project.basedir}/src/main/asyncapi/asyncapi.yaml</filePath>
                                    <supplier>
                                        <apiPackage>some.package.api.model.producer</apiPackage>
                                        <modelPackage>some.package.api.model</modelPackage>
                                        <useLombokModelAnnotation>true</useLombokModelAnnotation>
                                    </supplier>
                                </specFile>
                            </specFiles>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
```
When I try to generate the java classes via mvn clean install, I get the following exception:

```
Execution asyncapi of goal com.sngular:scs-multiapi-maven-plugin:5.0.1:asyncapi-generation failed: AsyncApi -> File System error trying to manipulate files: The following has evaluated to null or missing:
[ERROR] ==> exceptionPackage  [in template "templateSchema.ftlh" at line 50, column 10]
[ERROR] 
[ERROR] ----
[ERROR] Tip: If the failing expression is known to legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
[ERROR] ----
[ERROR] 
[ERROR] ----
[ERROR] FTL stack trace ("~" means nesting-related):
[ERROR] 	- Failed at: ${exceptionPackage}  [in template "templateSchema.ftlh" at line 50, column 8]
[ERROR] ----
```

Does anyone know how to solve this?

**Comment by jemacineiras** [comment]
HI @landoephan,

can you please provide the asyncapi yml file? It will help with the investigation.

Cheers

**Comment by landoephan** [comment]
Thanks for the quick reply, I found two issues:

1. the exception occurs, when I have required fields defined in my components schemas, e.g.:

```
components:
  messages:
      ...
  schemas:
    MyObject:
      type: object
      required:
        - idenficationNumber
      properties:
        idenficationNumber:
          type: string
          pattern: '^\d{8}$'
``` 

2. The second issue I encountered when I removed the required fields from my yml. The pattern validation uses `javax.validation` instead of jakarta.

Are there any fixes for these two issues?

**Comment by jemacineiras** [comment]
HI @landoephan ,

I will take a look to the first issue,
Second issue is set using a configuration flag `springbootversion` just remove it. By default we use `javax.validation` we only use the `jakarta` when that flag has a version number greater (or equal) than 3

**Comment by landoephan** [comment]
Hi @jemacineiras,

thank you, setting the springBootVersion worked :) I encountered another problem:

- when I use `allOf` in a schema (like here: https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/), I get the error message `Cannot invoke "com.fasterxml.jackson.databind.JsonNode.has(String") because "properties" is null`. In this case, null as properties should be a valid value, I guess.

**Comment by jemacineiras** [comment]
HI @landoephan ,
Glad the flag sorted it out.
Regarding the allOf can you please open another issue?
We have not a total support for these feature since is quite complex to face. If you can provide an example about your schema. it will help us a lot.
Cheers

**Comment by jemacineiras** [comment]
Closing as solved.
