### ISSUE TITLE
When specification contains word "new" generated files cannot be compiled

### ISSUE THREAD

**Issue by hebrayah** [sngular/scs-multiapi-plugin#295]
When AsyncAPI specificaiton file contain property named "new", causes Java file generation with property using reserved word - and generated files are not possible to compile.
In such case generated java field should be _new or something like that ...

**Comment by jemacineiras** [comment]
HI @hebrayah,
Can you please provide a use case about the situation you need such a feature?
Because  doesn't make anysense to modify the property building from the tool for only some special words. Keep in mind the code also generate Lombok annotated class you what you are suggesting is to generate something like

`public class Something
....
private Boolean _new;

.....`

so we should generate then `get_New()` and `set_New()` unless you want to we create special getter and setter for you unique case as `getNew()` and `setNew()`.

Please clarify.

**Comment by jemacineiras** [comment]
HI @hebrayah,

I just was playing around a bit with this request... may you try the branch I created?

Cheers

**Comment by hebrayah** [comment]
Hello, 

I have tried to replicate this issue on openapi-genearator. it handles this situation precisely the way i described, so:

![image](https://github.com/sngular/scs-multiapi-plugin/assets/17050568/d1f90eee-af24-4305-8d7a-9500a9e40fad)

Caused generation of:

```
  public static final String JSON_PROPERTY_NEW = "new";
  private GeographyRuleNew _new;

   /**
   * Get _new
   * @return _new
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NEW)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GeographyRuleNew getNew() {
    return _new;
  }


  @JsonProperty(JSON_PROPERTY_NEW)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNew(GeographyRuleNew _new) {
    this._new = _new;
  }


```

Bear in mind that method _new can be already generated and has different meaning.
`  public GeographyRule _new(GeographyRuleNew _new) {
    this._new = _new;
    return this;
  }
`

**Comment by hebrayah** [comment]
I do think that this behavior is just a problem between a reserved wors lists in two languages - so it should not impact the shape of the interface itself.

**Comment by jemacineiras** [comment]
Hi @hebrayah,
had you a chance to try the branch associated to this issus?

Cheers

**Comment by hebrayah** [comment]
Hi

Sorry for that delay,
U unfortunately i didnt have occasion to do that - however, as this is not
PR but just new branch - I am not familiar with code itself to judge if
changes are fine.
I hope i described desired output as a business analyst ;)

Best regards
marcin


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Nie
zawiera wirusów.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

czw., 5 paź 2023 o 10:18 Jose E. Garcia Maciñeiras ***@***.***>
napisał(a):

**Comment by hebrayah** [comment]
Awesome, thanks for the update!

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Nie
zawiera wirusów.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

śr., 25 paź 2023 o 11:35 Jose E. Garcia Maciñeiras ***@***.***>
napisał(a):
