### ISSUE TITLE
AsyncApi Interpreting of property "const" not possible

### ISSUE THREAD

**Issue by devNbis** [sngular/scs-multiapi-plugin#298]
Hi,
the interpreting of the property "const" in async api not possible

```json
"properties": {
  "specversion": {
     "const": "ConstantValue"
  }
}
```

**Comment by jemacineiras** [comment]
Hi @devNbis,

Thanks for the tip, we will added quite soon.
Can you add your expectations about how it should behave?

Cheers

**Comment by devNbis** [comment]
Hi @jemacineiras ,
Hm that's  the real question. I've found only const as String inside the AsyncApi samples. But is this always so?
On the implementation side Java convention is all constants with uppercase letters which breaks the  schema.
From my point of view the property should be private final and have only a getter.

```java
private final String sampleConst = "This is a sample";

public String getSampleConst(){
  return sampleConst;
}
```

This will also work with lombook.

Cheers
