### ISSUE TITLE
asyncApi String with format date or datetime

### ISSUE THREAD

**Issue by devNbis** [sngular/scs-multiapi-plugin#299]
The definition of 
```json
"validFrom": {
  "type": "string",
  "format": "date-time"
},
````
Will be interpreted only as String not as date.

**Comment by devNbis** [comment]
Hi @jemacineiras
I want to add the code for it  which is based on the branch 
293-asyncapi-$ref-resultion-are-always-a-class
I want to make a new branch for it. The version would then be 5.0.3  correct?
But the old one isn't merged and has the revision of 5.0.2

**Comment by jemacineiras** [comment]
Hi @devNbis 
This branch is still under review/development. Let us do the merge so you can open the issue or collaborate with the plugin.
Cheers

**Comment by gaby-roland** [comment]
This would be a cool improvement 👍

**Comment by devNbis** [comment]
Hi @jemacineiras 
I would like to add a branch for the changes
299-asyncApi-String-with-format-date-or-datetime
Is it possible to give me the rights?
Cheers

**Comment by jemacineiras** [comment]
HI @devNbis,
I added as collaborator, just follow the contributing rules and you can add your branch.

Cheers

**Comment by devNbis** [comment]
Hi @jemacineiras ,
I've added the branch and a pull request. But there are errors by the enhancement of the readme which follow the same  structure as the text above.
Cheers
