### ISSUE TITLE
Support for Multipart

### ISSUE THREAD

**Issue by oscar-ares** [sngular/scs-multiapi-plugin#328]
If an OpenApi defined API uses `multipart/form-data` in the request body to upload a file using:
```
file:
    type: string
    format: binary
```
The DTO generated defines the `file` field as a String, instead of MultipartFile object

It would be greatly appreciated if this feature could be added. Thank you!

**Comment by janDuinRod** [comment]
Hi! This issue is also affecting our project. Is the solution currently in progress?
