### ISSUE TITLE
Differences creating AsyncAPI Message Java classes between Multiapi v4 and v5

### ISSUE THREAD

**Issue by malon875875** [sngular/scs-multiapi-plugin#330]
Hello, 

I am using the valid asyncapi.yaml file below

**A)**
When using 
- id 'com.sngular.scs-multiapi-gradle-plugin' version **'4.9.12'**
then the created Java classes are 
![pluginoutput4](https://github.com/sngular/scs-multiapi-plugin/assets/25825966/762ffac1-e53a-47f2-ac2b-311afe533d6d)

containing Folder **messages** and **schemas**

</br>
</br>

**B)**
When using 
- id 'com.sngular.scs-multiapi-gradle-plugin' version **'5.3.4'**
then the created Java classes are 
![pluginoutput5](https://github.com/sngular/scs-multiapi-plugin/assets/25825966/5eab5c21-6a9b-4c9c-b78a-2be1eee1eb38)

there are no more Folders **messages** and **schemas**

- Have the the packages **messages** and **schemas** been removed on purpose starting with gradle plugin v5?
- Does this mean that **messages** and **schemas** are now combined into the Payload Java Class?

</br>
</br>

**AsyncAPI.yaml)**
```
asyncapi: 2.6.0
id: 'urn:com:rbinternational:cmi:ebam::service'
info:
  title: my api
  version: 1.0.1
servers:
  mgmt:
    url: >-
      pulsar://localhost:6650
    protocol: test
    description: test
defaultContentType: avro
channels:
  my-status-event-v1:
    subscribe:
      operationId: consumeInquiryStatusChange
      summary: foofoo
      description: >-
        foofoo
      message:
        $ref: '#/components/messages/ChangeEbamInquiryStatus'
        description: >-
          foofoo
        messageId: ChangeEbamInquiryStatusPublish
    publish:
      operationId: publishInquiryStatusChange
      summary: foofoo
      description: foofoo
      message:
        $ref: '#/components/messages/ChangeEbamInquiryStatus'
        description: >-
          foofoo
        messageId: ChangeEbamInquiryStatusConsume
components:
  messages:
    ChangeEbamInquiryStatus:
      name: changeEbamInquiryStatus
      title: Change Inquiry status
      summary: Changes the status of the eBAM process for a specific inquiry.
      traits:
        - $ref: '#/components/messageTraits/neuronHeader'
      payload:
        $ref: '#/components/schemas/changeEbamInquiryStatusPayload'
      contentType: avro
  schemas:
    changeEbamInquiryStatusPayload:
      type: object
      namespace: com.rbinternational.cmi.ebam.stream.model.event.schemas
      properties:
        agreementId:
          type: string
          description: >-
            The id associated with the agreement that the customer has with the
            bank
  messageTraits:
    neuronHeader:
      headers:
        type: object
        properties:
          producerName:
            description: >-
              Unique producer name derived from the unique application /
              component name.
            type: string
          eventTime:
            description: Timestamp in epoch when the business event occurred
            type: integer
            minimum: 0
            maximum: 4111892291
```

**Comment by jemacineiras** [comment]
HI @malon875875,

you are absolutely right. Reason to move from v4 to v5 was we decided to not generate Message Objects, we move to the standard Message from Spring. We did not find and use case where we need to use the Message and the Payload, so only generate the Payload looks enough to be able to send data and make the generated code more simple.
Did you find a use case where you need that message object?
Going over your `yaml` file I can see you are using headers, may be is that missing now?
Cheers
