### ISSUE TITLE
Default Constructor Generation in Payload Classes - Spring Boot

### ISSUE THREAD

**Issue by WZHMIJJ** [sngular/scs-multiapi-plugin#332]
I have integrated the `sngular/scs-multiapi-plugin` Gradle plugin into my Spring Boot application to generate POJOs for AVRO schemas to be used with Pulsar. However, I encountered an issue where the generated domain objects lack a default constructor, leading to internal exceptions when using Jackson to deserialize the objects in the Pulsar listener.

I believe the plugin could be enhanced or maybe even has a posibility in one of two ways to address this issue:
1. Include an option to generate a default constructor for payload classes.
2. Provide support for the builder pattern when generated payload classes are used in Spring Boot.

Adding either of these features would greatly improve the compatibility of the plugin with Spring Boot Pulsar Starter.

I kindly request the addition of this feature to the plugin to improve its usability in various environments. Thank you for your consideration.

**Comment by malon875875** [comment]
The  sngular/scs-multiapi-plugin Gradle plugin vesion used is id 'com.sngular.scs-multiapi-gradle-plugin' version '5.3.5'

**Comment by jemacineiras** [comment]
Hi @malon875875, @WZHMIJJ,

That is odd because we are using the pattern builder in our generated POJOS, also if you are using Lombok @Builder annotation is added.

Can we get an example of the API you are trying to build?

Cheers

**Comment by WZHMIJJ** [comment]
Yes, the builder is truly added, but the problem arrises that inside of Spring it does not instantiate the object. The problem is because of the domain object missing a default constructor and thus Jackson throws an internal exception.

**Comment by jemacineiras** [comment]
Hi, I just refactor all the DTOs in order to be the same for all generators. May you check new release please?
