### ISSUE TITLE
Fix responses with no body return Void

### ISSUE THREAD

**Issue by carlosaf-sngular** [sngular/scs-multiapi-plugin#336]
The generated code for 204 responses has return type Void and tries to return a non existent body.

## Example

Yaml specification:
<img width="578" alt="Captura de pantalla 2024-03-27 a las 9 43 25" src="https://github.com/sngular/scs-multiapi-plugin/assets/165148531/549aca63-5d6c-4c1a-8a4e-54a0977c67e3">

Generated code:
<img width="734" alt="Captura de pantalla 2024-03-27 a las 9 44 08" src="https://github.com/sngular/scs-multiapi-plugin/assets/165148531/558b003d-6091-4581-aa18-c2457002b3d0">

**Comment by jemacineiras** [comment]
Already solved
