### ISSUE TITLE
Gradle configuration does not generate classes

### ISSUE THREAD

**Issue by slin86** [sngular/scs-multiapi-plugin#338]
We are trying to get this plugin to run with gradle. We have an ASYNC Api definition and want to generate the Api. However, only the "generated-source" folder is created, but no classes are created. In addition, no error is output.

We have already been able to generate code with Maven, so we assume that our asyncapi.yml should be correct. We have also tried the yaml file from the test folder of the project, but here too the folder remains empty.

At root level, the configuration looks like this:

```
plugins {
    id 'org.springframework.boot' version '3.1.6'
    id 'io.spring.dependency-management' version '1.1.4'
    id 'java'
    id 'maven-publish'
    id 'io.freefair.lombok' version '8.6'
    id 'com.sngular.scs-multiapi-gradle-plugin' version '5.4.1'
}

asyncapimodel {
    specFile {
        {
            filePath = './src/main/resources/test-service.yaml'
            consumer {
                apiPackage = 'en.abc.test.asyncapi'
                modelPackage = 'en.abc.test.asyncapi.model'
            }
        }
        springBootVersion = 3
        overWriteModel = true
    }
}
```

**Comment by slin86** [comment]
I think, this could be closed

**Comment by JerryngtonD** [comment]
@slin86 hello :)
could you help me at this problem ? How did you resolve this problem ?
I faced off with same things.

**Comment by slin86** [comment]
Hey @JerryngtonD ,
after adding some ids from api spec file, then it was working for us. The autoresolve of consumer did not work for us.

For example: 

```
asyncapimodel {
    specFile {
        {
            filePath = './src/main/resources/test-service.yaml'
            consumer {
                ids = 'consumerA,consumerB'
                apiPackage = 'en.abc.test.asyncapi'
                modelPackage = 'en.abc.test.asyncapi.model'
            }
        }
        springBootVersion = 3
        overWriteModel = true
    }
}
```
